plugins {
    id 'java'
    id 'application'
}

group 'com.systemdesign'
version '1.0-SNAPSHOT'

application {
    mainClassName = 'chapter05.Application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    implementation 'com.google.guava:guava:33.2.0-jre'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
            compileClasspath += main.output
            runtimeClasspath += main.output
        }
    }
}
